# Site Settings
title: "The Rise and Fall of Market Dynasties"
description: "A Data Story"
author: Hamahem
url: "https://hamahem.github.io"
baseurl: "/datastory"
remove-ads: true
# Navigation
navbar-links:
  Home: "index"

# Logo
avatar: "/assets/img/hamahem_logo.png"
round-avatar: false
footer-logo: "/assets/img/epfl_logo.svg"

url-pretty: "hamahem.github.io"

# Colors
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# navbar-col: "#EAEAEA"
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# footer-col: "#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# footer-hover-col: "#0085A1"

page-col: "#F4F5F7"

# Text: Stark Black (Heavy, authoritative)
text-col: "#121212"

# Links: International Orange (The "Alert" / Revolution color)
link-col: "#FF3300"

# Hover: Steel Blue (The cold corporate machine)
hover-col: "#2C3E50"

# Navbar: Raw Concrete
navbar-col: "#E0E0E0"
navbar-text-col: "#000000"
# A heavy, black border is essential for Brutalism
navbar-border-col: "#000000"

# Footer: Inverted (Heavy base)
footer-col: "#121212"
footer-text-col: "#CCCCCC"
footer-link-col: "#FF3300"
footer-hover-col: "#FFFFFF"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
