# Site Settings
title: "The Rise and Fall of Market Dynasties"
description: "A Data Story"
author: Hamahem

# Navigation
navbar-links:
  Home: "index"

# Logo
avatar: "/assets/img/hamahem_logo.png"
round-avatar: false

# Colors
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
