# Site Settings
title: "The Rise and Fall of Market Dynasties"
description: "A Data Story"
author: Hamahem
url: "https://hamahem.github.io"
baseurl: "/datastory"
remove-ads: true
# Navigation
navbar-links:
  Home: "index"

# Logo
avatar: "/assets/img/hamahem_logo.png"
round-avatar: false
footer-logo: "/assets/img/epfl_logo.svg"

url-pretty: "hamahem.github.io"

# Colors
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# navbar-col: "#EAEAEA"
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# footer-col: "#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# footer-hover-col: "#0085A1"

page-col: "#FAFAF8"
text-col: "#1A1A1A"
link-col: "#CB6843"
hover-col: "#B87333"
navbar-col: "#2F4858"
navbar-text-col: "#FAFAF8"
navbar-border-col: "#1A1A1A"
footer-col: "#2F4858"
footer-text-col: "#FAFAF8"
footer-link-col: "#CB6843"
footer-hover-col: "#B87333"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
